### ISSUE TITLE
Unify duplicate implementation of HNHN

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/TopoModelX#157]
# What?

There were two implementations of HNHN by challenge participants.

If they are indeed the same implementation, we need to merge them into 3 files:
- hnhn_layer.py
- test_hnhn_layer.py
- hnhn_train.ipynb

If they are different implementations, we need to check if one of them can be deleted. 
Possible reasons to delete:
- not faithful to the research paper introducing HNHN,
- incomplete implementation.

If we decide to keep both of them, the file names and docstrings should be updated to highlight their difference.

# Why?

Because it is confusing to have two implementations of HNHN without knowing their difference.

# Where?

The files to modify are:
- topomodelx/nn/hypergraph/hnhn_layer.py
- topomodelx/nn/hypergraph/hnhn_layer_bis.py
- test/nn/hypergraph/test_hnhn_layer.py
- test/nn/hypergraph/test_hnhn_layer_bis.py
- tutorials/hypergraph/hnhn_train.ipynb
- tutorials/hypergraph/hnhn_train_bis.ipynb

# How?

See for example how the duplicate SCN and SCN2 has been solved and the use of the "See Also" sections in their docstrings.

**Comment by ninamiolane** [comment]
@gurug-dev any update on this?

**Comment by levtelyatnikov** [comment]
@gurug-dev, no worries, I will take care of it
