### ISSUE TITLE
Unify duplicate implementation of Scone

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/TopoModelX#159]
# What?

There were two implementations of Scone by challenge participants.

If they are indeed the same implementation, we need to merge them into 3 files:
- scone_layer.py
- test_scone_layer.py
- scone_train.ipynb

If they are different implementations, we need to check if one of them can be deleted. 
Possible reasons to delete:
- not faithful to the research paper introducing Scone,
- incomplete implementation.

If we decide to keep both of them, the file names and docstrings should be updated to highlight their difference.

# Why?

Because it is confusing to have two implementations of Scone without knowing their difference.

# Where?

The files to modify are:
- topomodelx/nn/simplicial/scone_layer.py
- topomodelx/nn/simplicial/scone_layer_bis.py
- test/nn/simplicial/test_scone_layer.py
- test/nn/simplicial/test_scone_layer_bis.py
- tutorials/simplicial/tscone_train.ipynb
- tutorials/simplicial/tscone_train_bis.ipynb

# How?

See for example how the duplicate SCN and SCN2 has been solved and the use of the "See Also" sections in their docstrings.

**Comment by ninamiolane** [comment]
TODO: Correct the text in the intro of the scone_bis.ipynb, that currently mentions HSN.

**Comment by michaelschaub** [comment]
See PR  #188
