### ISSUE TITLE
Fix tutorials' display on TopoModelX doc's website

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/TopoModelX#162]
# What?

The Tutorials Tab of TopoModelX's documentation website does not display the tutorials properly.
https://pyt-team.github.io/topomodelx/tutorials/index.html

Specifically, the headers of every tutorials shows up which clutters the page without providing any useful information:
```
Tutorials
[Train a Cellular Attention Network (CAN)](https://pyt-team.github.io/topomodelx/notebooks/cell/can_train.html)
[Set-up](https://pyt-team.github.io/topomodelx/notebooks/cell/can_train.html#Set-up)
[Pre-processing](https://pyt-team.github.io/topomodelx/notebooks/cell/can_train.html#Pre-processing)
[Create the Neural Network](https://pyt-team.github.io/topomodelx/notebooks/cell/can_train.html#Create-the-Neural-Network)
[Train the Neural Network](https://pyt-team.github.io/topomodelx/notebooks/cell/can_train.html#Train-the-Neural-Network)
[Train the Neural Network with Attention](https://pyt-team.github.io/topomodelx/notebooks/cell/can_train.html#Train-the-Neural-Network-with-Attention)
[Train a Convolutional Cell Complex Network (CCXN)](https://pyt-team.github.io/topomodelx/notebooks/cell/ccxn_train.html)
[Set-up](https://pyt-team.github.io/topomodelx/notebooks/cell/ccxn_train.html#Set-up)
```
Etc...

We need to prevent these headers to appear, so that only the thumbnails of the tutorials are shown.

# Why?

Because displaying headers of tutorials does not provide any useful information and clutters the page.

# Where?

On TopoModelX, modify the documentation website's "tutorials" tab by modifying:
https://github.com/pyt-team/TopoModelX/tree/main/docs/tutorials

# How?

Maybe the `:maxdepth: 1` parameter can be tuned?

**Comment by ninamiolane** [comment]
![Image](https://github.com/pyt-team/TopoModelX/assets/8267869/a4d31e07-81e5-4b8a-ab17-0bcd2ecaf75a)

**Comment by devendragovil** [comment]
@ninamiolane  

The tutorial website for me opens up like this:

<img width="1356" alt="image" src="https://github.com/pyt-team/TopoModelX/assets/39613474/d1b96880-e6f5-4d10-ac76-6c6536133aaf">

**Comment by devendragovil** [comment]
@ninamiolane 
Would you like me to remove the Section Navigation on the left?

**Comment by ninamiolane** [comment]
@devendragovil indeed, the display of the tutorials has changed (and improved) since this task was done.

Tasks that remain:
- [ ] FIX: Make the titles consistents
Many tutorials have the title "Train a Hypergraph Neural Network". That is not precise enough. 
Let's modify the tutorials titles so that they are of the form "Train a [name of the model] ([abbreviation of the model])". 
For example: "Train a Cell Attention Network (CAN)".
- [ ] If needed, clean the Navigation section on the left.
By updating the titles, the Navigation section might become more readable already.
Clean it such that only the titles of the tutorials appear, but not their sections' titles. 
No need to remove it entirely.

Thanks!
