### ISSUE TITLE
Merge HOAN models from challenge's PRs

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/TopoModelX#164]
# What?

There were two implementations of HOAN models from Hajij 22a by challenge participants, in the PRs:
https://github.com/pyt-team/TopoModelX/pull/145/files
https://github.com/pyt-team/TopoModelX/pull/104/files

Both PRs fail the unit-tests.
It is also unclear whether the PRs implement the same HOAN model, or different models from Hajij22a.

If they are implementing the same HOAN model, we need to merge them into 3 files:
- hoan_layer.py
- test_hoan_layer.py
- hoan_train.ipynb

If they are different implementations, we need to check if one of them can be deleted. 
Possible reasons to delete:
- not faithful to the research paper introducing HOAN,
- incomplete implementation.

If we decide to keep both of them, the file names and docstrings should be updated to highlight their difference.

# Why?

These PRs represent our only implementation of the `combinatorial_complex` domain which is currently not represented in topomodelx. We need to merge them so that this domain is represented as well.

# Where?

The files to add should look like:
- topomodelx/nn/combinatorial/hoan_layer.py
- test/nn/combinatorial/test_hoan_layer.py
- tutorials/combinatorial/hoan_train.ipynb

If the two PRs are actually implementing different models, then we should have 2 sets of 3-files (one set for each model) with explicit names and documentation that reflect the differences between the models.

# How?

See for example how the duplicate SCN and SCN2 has been solved and the use of the "See Also" sections in their docstrings.

**Comment by ninamiolane** [comment]
@mhajij if you can help on this one it would be great! Assigning you for now.

**Comment by mhajij** [comment]
> @mhajij if you can help on this one it would be great! Assigning you for now.

Got it.

**Comment by mhajij** [comment]
#145 does not match the HOAN implementation so it will not be merged into the main repo.
#104 has been merged into the main repo sucessfully.
