### ISSUE TITLE
Fix API Reference on Topomodelx' doc website

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/TopoModelX#165]
# What?

The API Reference Tab of TopoModelX's documentation website is broken.
https://pyt-team.github.io/topomodelx/api/index.html

It is broken because it does not show the Python classes and functions, and their docs, that are implemented in the package.
By contrast, the API Reference Tab of TopoNetX is not broken (at least at the time of submission of this issue), and looks like this:
https://pyt-team.github.io/toponetx/api/index.html

(see also Screenshot below, in the case the API Reference Tab of TopoNetX does break after this issue is submitted).

We need to fix the API Reference Tab of TopoModelX.

# Why?

Because the API Reference is one of the most important aspect of the documentation website. It needs to show which functions are implemented in the package.

# Where?

On TopoModelX, modify the documentation website's "api" tab by modifying files in the folder:
https://github.com/pyt-team/TopoModelX/tree/main/docs/api

# How?

Look at how the API Reference Tab is coded in TopoNetX, by looking at the files in this folder:
https://github.com/pyt-team/TopoNetX/tree/main/docs/api

Detect what differs between TopoModelX and TopoNetX, and fix TopoModelX accordingly.

The main difference is probably that TopoModelX has an additional layer of folder structure, that needs to be correctly processed.

**Comment by ninamiolane** [comment]
![Image](https://github.com/pyt-team/TopoModelX/assets/8267869/7c11b4b0-7f76-4b7a-9d62-3142c524f8ef)

**Comment by ninamiolane** [comment]
The API Reference of TopoModelX does not display the API of the functions:


![Image](https://github.com/pyt-team/TopoModelX/assets/8267869/78990b82-29b9-4731-a9be-6225c19df879)

**Comment by devendragovil** [comment]
The issue hasn't been fixed completely, but API reference should be visible now.

**Comment by ninamiolane** [comment]
@devendragovil I'm re-opening this issue since it is not solved.

There seems to be only one neural layer on each domain that appears, e.g. only the TemplateLayer for Hypergraph. We need all of them to appear in the documentation.

This should be as easy as copy pasting the necessary lines of the form:
```
.. automodule:: topomodelx.nn.hypergraph.template_layer
   :members:
```
into that file:

https://github.com/pyt-team/TopoModelX/blob/main/docs/api/nn.rst

**Comment by ninamiolane** [comment]
Copy-pasting @ffl096 'comment:

We document everything on a single page, something no other popular package I know does. Every class should have its own page in the documentation. Then there wouldn't be any reference clashes and everything works fine. We don't have to reinvent anything here, look how NetworkX and others do it, e.g., https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.isomorphism.is_isomorphic.html

@devendragovil would it be possible to do this?

**Comment by devendragovil** [comment]
Yes, I would do that. @ninamiolane

**Comment by ninamiolane** [comment]
Thank you so much @devendragovil .

I'm adding the high-priority label to this, because this task is blocking others.
