### ISSUE TITLE
Add tutorials' thumbnails on TopoModelX doc website

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/TopoModelX#169]
# What?

The tutorials webpage of TopoModelX documentation website does not display any thumbnails.

https://pyt-team.github.io/topomodelx/tutorials/index.html

We should add thumbnails.

# Why?

The tutorials webpage is one of the first pages that users see. It should look clean.

Additionally, thumbnails help the reader understanding what the tutorials are about.

# Where and How?

In order to add thumbnails, we refer to the similar github issue that added thumbnails for the tutorials of TopoNetX:
https://github.com/pyt-team/TopoNetX/issues/84

The PR solving the issue was:
https://github.com/pyt-team/TopoNetX/pull/179

The persons solving the issue were: @devendragovil and @mhajij: ask them for guidelines if needed.

For each tutorial notebook:
1. Locate the tensor diagram corresponding to the neural network implemented in the notebook in [Fig. 11](https://github.com/pyt-team/TopoModelX/blob/main/topomodelx.jpeg) of the review [Architectures of Topological Deep Learning: A Survey of Topological Neural Networks](https://arxiv.org/pdf/2304.10031.pdf).
2. Crop the tensor diagram out of the figure.
3. Make this tensor diagram the thumbnail of the notebook.

**Comment by mhajij** [comment]
@devendragovil you fixed this for toponetx, can you do the same for topomodelx please?

Thanks

**Comment by devendragovil** [comment]
@mhajij @ninamiolane  Definitely Professor. Will start on this asap.

**Comment by devendragovil** [comment]
@mhajij  I am estimating I should be able to close this issue by Saturday EOD.

**Comment by ninamiolane** [comment]
> I would also like advice on what thumbnails are appropriate:

@devendragovil yes please use the tensor diagram corresponding to the notebook as the thumbnail:

See details in the text above, copy-pasted here again for convenience:

Locate the tensor diagram corresponding to the neural network implemented in the notebook in [Fig. 11](https://github.com/pyt-team/TopoModelX/blob/main/topomodelx.jpeg) of the review [Architectures of Topological Deep Learning: A Survey of Topological Neural Networks](https://arxiv.org/pdf/2304.10031.pdf).

**Comment by devendragovil** [comment]
@ninamiolane 

I have updated the thumbnails with tensor diagrams, I came across the following issues though:

1. Same Tensor Diagram: There are multiple notebooks for (seemingly) same model. These include, examples:
    a. can_train_bis and can_train
    b. allset_train and allset_transformer_train
    c. hnhn_train_bis and hnhn_train 
2. Unavailable Model Tensor: 
    a. Can't find any model named ccxn (for ccxn_train) in [Fig 11](https://github.com/pyt-team/TopoModelX/blob/main/topomodelx.jpeg). However the notebook is about Hajij (2020) so I used tensor diagram for cxn Hajij (2020)
    b. template_train notebook in Hypergraph (As of now thumbnail is a generic hypergraph)
3. Multiple tensor diagrams: Some models have multiple tensor diagrams like CXN, Hajij (2020), HSN Hajij22b
4. No clear screenshot: I was unable to take clear screenshots for some models due to encroachment of nearby tensor diagrams. @ninamiolane  Wanted your opinion. Are the current thumbnails acceptable or should I also edit them? Example: 
    a. CWN, Bodnar21b
    b. Dist2Cycle, Keros22
    c. SAN, Giusti22a
5. Curious case of sccn_train: There is no sccn tensor diagram, however there is a scnn and the notebook of sccn seems to be pointing to the same author, year combination (Yang 22). However, there is another notebook with scnn. For now, sccn_train has thumbnail for scnn.
6. There is scn2_train. Is it the same as scn?
7. Scone_train_bis notebook seems to be referring to HSN Hajij 22, rather than the roddenberry paper. For now, both scone_train_bis and scone_train have the same tensor diagram

**Comment by ninamiolane** [comment]
Thank you so much for summarizing the issues you encountered so clearly. It's extremely helpful. Answers below!

1. Same Tensor Diagram: There are multiple notebooks for (seemingly) same model. These include, examples:
- [x] a. can_train_bis and can_train --> yes, use the same tensor diagram for these
- b. allset_train and allset_transformer_train --> these are different: 
  - [ ] allset_train: AllSet Chien22 from the "Standard convolution" Column
  - [ ] allset_transformer_train:  AllSet Chien22 from the "Attentional Convolutional/General" Column
<img width="397" alt="Screen Shot 2023-09-06 at 10 23 54 PM" src="https://github.com/pyt-team/TopoModelX/assets/8267869/874ce27b-98ea-44bf-96f2-1e38a29e7b69">

- [x] c. hnhn_train_bis and hnhn_train --> yes, use the same tensor diagram for these

Unavailable Model Tensor:
- [x] a. ccxn_train --> Ok like this. Could you add the following sentence to the notebook: "Note that this implements the convolutional version of a CXN  whose tensor diagrams are given by [add thumbnail]." See my answer on the "Multiple tensor diagrams" point below.
- [x] b. template_train --> Ok like this. this is not a model of the literature, thus OK like this. We might even delete this one in the future.

Multiple tensor diagrams: Some models have multiple tensor diagrams like CXN, Hajij (2020), HSN Hajij22b
- [ ] Yes, but in the code, only one of these diagrams is implemented. Find out which one it is (e.g. by looking at the names of the neighboring matrices) and screenshot only this one.

No clear screenshot: 
- [ ] I will send you an editable figure so that you can isolate the diagrams.

- [ ] Curious case of sccn_train --> Indeed, there is a typo in figure 11. SCCN should be the tensor diagram corresponding to the leftmost Yang22c in figure 11. (NOT SCNN as you currently have it.) See issue #175 for details.

- [x] There is scn2_train. Is it the same as scn --> Yes, but only for cells of rank <=2. OK to use the tensor diagram of SCN.
- [x] For now, both scone_train_bis and scone_train have the same tensor diagram --> Good like this!
