### ISSUE TITLE
Check that "References" render correctly on documentation websites

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/TopoModelX#173]
# What?

The docstrings of several functions have a Reference section that looks like:

```
    References
    ----------
    .. [AGRW20] Devanshu Arya, Deepak K Gupta, Stevan Rudinac and Marcel Worring.
        HyperSAGE: Generalizing inductive representation learning on hypergraphs.
        arXiv preprint arXiv:2010.04558. 2020
```

Within the docstrings, the papers are cited via `in [AGRW20]` or maybe via `in _[AGRW20]` (using an underscore?).

We should make sure that each docstring:
- cites the paper that their function is implementing,
- cites it "correctly" in the sense that the References section appears cleanly on the documentation website.

Note: this issue is blocking on Issue , which should be completed first.

# Why?

Because we want to give credit to the authors of the corresponding papers.
Because it will help the users of the codebase to know in which paper they can find the theory corresponding to the code they are trying to run.

# Where?

Everywhere.

# How?

Check on the documentation website that the references look great by going to:
https://pyt-team.github.io/topomodelx/api/index.html

**Comment by ninamiolane** [comment]
This is an example of how the References section of a docstring looks like on the documentation website.

![Image](https://github.com/pyt-team/TopoModelX/assets/8267869/b12feb43-fcf4-4464-9a1a-e7503476fdb2)

**Comment by ninamiolane** [comment]
This is currently blocked by issue #165

**Comment by papamarkou** [comment]
This is no longer blocked. Replacing alphanumeric with numeric references throughout solves the rendering of references. I am nearly half way, having sorted the base and cells, so probably by tomorrow this will be ready to merge.

**Comment by papamarkou** [comment]
Closing the issue, as it has been address via [this PR for TopoModelX](https://github.com/pyt-team/TopoModelX/pull/200).
