### ISSUE TITLE
Complete writing tasks on overleaf

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/TopoModelX#187]
See TODO's in overleaf

**Comment by papamarkou** [comment]
- [x] Abstract
- [x] Introduction
- [ ] Implementation overview
- [ ] Comparison and interaction with other packages
- [ ] Usage: elementary examples
- [ ] Conclusion

**Comment by ninamiolane** [comment]
Let's remove the conclusion: we do not have enough space for it. I'll tick the box in your checklist.
