### ISSUE TITLE
Check docstrings everywhere

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/TopoModelX#210]
# What?

Some docstrings are erroneous, for example:
```

class SCNN(torch.nn.Module):
    """Simplicial convolutional neural network implementation for complex classification.

    Note: At the last layer, we obtain the output on simplcies, e.g., edges.
    To perform the complex classification task for this challenge, we consider pass the final output to a linear layer and compute the average.

    Parameters
    ----------
    in_channels: int
        Dimension of input features
    intermediate_channels: int
        Dimension of features of intermediate layers
    out_channels: int
        Dimension of output features
    conv_order_down: int
        Order of lower convolution
    conv_order_up: int
        Order of upper convolution
    n_layers: int
        Numer of layers
    """

    def __init__(
        self,
        in_channels,
        intermediate_channels,
        out_channels,
        conv_order_down,
        conv_order_up,
        aggr_norm=False,
        update_func=None,
        n_layers=2,
    ):
```

# How?

Check docstrings in the whole codebase and correct them if needed. Check that:
- the format of the docstring is correct
- the docstring documents every input and output variable

Follow docstrings' guidelines written in our contribution file: https://pyt-team.github.io/topomodelx/contributing/index.html#write-documentation

**Comment by papamarkou** [comment]
Everyone, I assigned this to @jarpri :)

**Comment by ninamiolane** [comment]
Completed on TopoModelX via PR #223 .

@jarpri can you check TopoNetX and TopoEmbedX as well? Thanks

**Comment by ninamiolane** [comment]
See also: https://github.com/pyt-team/TopoNetX/issues/95

**Comment by ninamiolane** [comment]
@jarpri @papamarkou what is the status on this?

**Comment by USFCA-MSDS** [comment]
@gurug-dev, @devendragovil @maneelusf  is this task closed now for TopoModelX ?
