### ISSUE TITLE
repository for TopoModelX  not found

### ISSUE THREAD

**Issue by fbarfi** [pyt-team/TopoModelX#282]
error message in trying to copy git clone: 
git clone git@github.com:pyt-team/TopoModelX.git                                  128 ↵ ──(Thu,Aug22)─┘
cd TopoModelX
Cloning into 'TopoModelX'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by ffl096** [comment]
Hello,

Your SSH keys are not set up correctly. Either add the correct key to your GitHub account or try HTTPS-based cloning. You can find more information here: https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository

Either way, this is not an issue with TopoModelX, so closing here :)

**Comment by fbarfi** [comment]
I was trying to install TopoModelX using the link the was given in the GitHub site for TopoModelX

**Comment by ffl096** [comment]
I understood that, but still you have to have ssh set up correctly or use https-based cloning.

> [git@github.com](mailto:git@github.com): Permission denied (publickey).

This is a GitHub permission issue, we don't have anything to do with that :)

**Comment by fbarfi** [comment]
I followed your advice and everything is good. I needed to create an SSH key.  THANKS!
