### ISSUE TITLE
Persistence Homology and Persistence diagram

### ISSUE THREAD

**Issue by fbarfi** [pyt-team/TopoModelX#283]
New to TopoModelX; wondering how to use this for persistence homology and how to obtain persistence diagram? If this makes sense. thanks.

**Comment by wardjm** [comment]
Hello. That's not really what this library is about. It depends on your application. There's a ripser binding in Python. Or if you know scikit-learn, there's scikit-tda. But there are a bunch of others as well. You can research for your use case.

**Comment by fbarfi** [comment]
Thanks.
